import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

// Serves per-project actual-vs-scheduled deviation data generated by the
// backend pipeline (backend/main.py -> frontend/public/data/timeline.json).
export async function GET() {
  try {
    const filePath = path.join(process.cwd(), "public", "data", "timeline.json");
    const raw = fs.readFileSync(filePath, "utf8");
    return NextResponse.json(JSON.parse(raw));
  } catch (error) {
    console.error("Failed to load timeline.json:", error);
    return NextResponse.json(
      { error: "Timeline data not generated yet. Run the backend pipeline (python main.py)." },
      { status: 404 },
    );
  }
}
