import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

// Serves quarterly inspection log summaries generated by the backend
// pipeline (backend/main.py -> frontend/public/data/reports.json).
export async function GET() {
  try {
    const filePath = path.join(process.cwd(), "public", "data", "reports.json");
    const raw = fs.readFileSync(filePath, "utf8");
    return NextResponse.json(JSON.parse(raw));
  } catch (error) {
    console.error("Failed to load reports.json:", error);
    return NextResponse.json(
      { error: "Report data not generated yet. Run the backend pipeline (python main.py)." },
      { status: 404 },
    );
  }
}
