import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

// Serves the LP-optimized inspector deployment schedule generated by the
// backend pipeline (backend/main.py -> frontend/public/data/assignments.json).
export async function GET() {
  try {
    const filePath = path.join(process.cwd(), "public", "data", "assignments.json");
    const raw = fs.readFileSync(filePath, "utf8");
    return NextResponse.json(JSON.parse(raw));
  } catch (error) {
    console.error("Failed to load assignments.json:", error);
    return NextResponse.json(
      { error: "Assignment data not generated yet. Run the backend pipeline (python main.py)." },
      { status: 404 },
    );
  }
}
