import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";

// Serves the PPDO inspector roster with LP-computed capacity/workload,
// generated by the backend pipeline (backend/main.py -> frontend/public/data/inspectors.json).
export async function GET() {
  try {
    const filePath = path.join(process.cwd(), "public", "data", "inspectors.json");
    const raw = fs.readFileSync(filePath, "utf8");
    return NextResponse.json(JSON.parse(raw));
  } catch (error) {
    console.error("Failed to load inspectors.json:", error);
    return NextResponse.json(
      { error: "Inspector roster not generated yet. Run the backend pipeline (python main.py)." },
      { status: 404 },
    );
  }
}
